# -*- coding: utf-8 -*-
"""concept_drift/drift_detector

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1htvzAgxnwl9LbO_MiDiEPqOGxAHFkoGD
"""

import pandas as pd
import numpy as np
from scipy.stats import ks_2samp
import matplotlib.pyplot as plt
import streamlit as st # Import streamlit here as it's used directly in the function

def run_concept_drift_check(df_path='data/final_dataset.csv', split_date='2024-11-01'):
    """
    Checks for concept drift in 'Quantity_Sold' using KS test.
    This function is designed to be called directly within a Streamlit app.

    Args:
        df_path (str): Đường dẫn đến file CSV dữ liệu cuối cùng.
        split_date (str): Ngày để phân chia dữ liệu (format 'YYYY-MM-DD').
    """
    st.subheader("Kiểm tra Concept Drift (Thay đổi phân phối dữ liệu)")
    st.write("---")

    try:
        df = pd.read_csv(df_path)
    except FileNotFoundError:
        st.error(f"Lỗi: Không tìm thấy file dữ liệu tại '{df_path}'. Vui lòng đảm bảo file 'final_dataset.csv' có sẵn.")
        return

    df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d')

    before_split_data = df[df['Date'] < split_date]['Quantity_Sold'].dropna()
    after_split_data = df[df['Date'] >= split_date]['Quantity_Sold'].dropna()

    if before_split_data.empty or after_split_data.empty:
        st.warning("Không đủ dữ liệu để thực hiện KS Test. Đảm bảo có dữ liệu trước và sau ngày phân chia đã chọn.")
        return

    ks_statistic, p_value = ks_2samp(before_split_data, after_split_data)

    st.write(f"**Ngày phân chia dữ liệu:** Trước vs Sau {split_date}")
    st.write(f"**KS Statistic:** `{ks_statistic:.4f}`")
    st.write(f"**P-value:** `{p_value:.4f}`")

    if p_value < 0.05:
        st.markdown(f"**Kết luận:** Có dấu hiệu **Concept Drift** (P-value < 0.05). Phân phối 'Quantity_Sold' thay đổi đáng kể giữa trước và sau tháng 11/2024.")
    else:
        st.markdown(f"**Kết luận:** Không có đủ bằng chứng để kết luận Concept Drift (P-value >= 0.05).")

    fig, ax = plt.subplots(figsize=(10, 6))
    ax.hist(before_split_data, bins=30, alpha=0.5, label=f'Before {split_date}', color='blue')
    ax.hist(after_split_data, bins=30, alpha=0.5, label=f'After {split_date}', color='red')
    ax.legend(loc='upper right')
    ax.set_title(f'Phân phối Quantity_Sold trước và sau {split_date}')
    ax.set_xlabel('Quantity_Sold')
    ax.set_ylabel('Frequency')
    st.pyplot(fig)
    st.write("---")
