# -*- coding: utf-8 -*-
"""utils/metrics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fuEAoQX3aYtiGE8zvThIlNJP13yEihib
"""

import numpy as np

def mean_absolute_percentage_error(y_true, y_pred):
    """
    Tính toán Mean Absolute Percentage Error (MAPE).

    Args:
        y_true (np.array or pd.Series): Giá trị thực tế.
        y_pred (np.array or pd.Series): Giá trị dự đoán.

    Returns:
        float: Giá trị MAPE. Trả về float('inf') nếu tất cả y_true đều bằng 0.
    """
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    non_zero_true = y_true != 0
    if not np.any(non_zero_true):
        return float('inf')
    return np.mean(np.abs((y_true[non_zero_true] - y_pred[non_zero_true]) / y_true[non_zero_true])) * 100
